apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-cpu-app
  namespace: k8s-optimizer
  labels:
    app: high-cpu-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: high-cpu-app
  template:
    metadata:
      labels:
        app: high-cpu-app
        tier: backend
    spec:
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args:
            - "--cpu"
            - "1"
            - "--io"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "32M"
            - "--timeout"
            - "3600s"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: high-cpu-app
  namespace: k8s-optimizer
spec:
  selector:
    app: high-cpu-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
