apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive-app
  namespace: k8s-optimizer
  labels:
    app: memory-intensive-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-intensive-app
  template:
    metadata:
      labels:
        app: memory-intensive-app
        tier: backend
    spec:
      containers:
        - name: memstress
          image: polinux/stress
          command: ["stress"]
          args:
            - "--vm"
            - "2"
            - "--vm-bytes"
            - "128M"
            - "--vm-hang"
            - "1"
            - "--timeout"
            - "3600s"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: memory-intensive-app
  namespace: k8s-optimizer
spec:
  selector:
    app: memory-intensive-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
